const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('klixa', {
  getConfig: () => ipcRenderer.invoke('config:get'),
  saveConfig: (config, integrationId) => ipcRenderer.invoke('config:save', config, { integrationId }),
  hueRegister: (bridgeIp, bridgePort) => ipcRenderer.invoke('hue:register', { bridgeIp, bridgePort }),
  hueDisconnect: () => ipcRenderer.invoke('hue:disconnect'),
  smallrigDiscover: (timeoutMs) => ipcRenderer.invoke('smallrig:discover', { timeoutMs }),
  smallrigProvision: (bleDeviceId, deviceUuid, name) => ipcRenderer.invoke('smallrig:provision', { bleDeviceId, deviceUuid, name }),
  smallrigForget: (uuid, forceLocal = false) => ipcRenderer.invoke('smallrig:forget', { uuid, forceLocal }),
  smallrigReconfigure: (uuid) => ipcRenderer.invoke('smallrig:reconfigure', { uuid }),
  smallrigList: () => ipcRenderer.invoke('smallrig:list'),
  smallrigPower: (uuids, on, level) => ipcRenderer.invoke('smallrig:power', { uuids, on, level }),
  smallrigColor: (uuids, color, brightness) => ipcRenderer.invoke('smallrig:color', { uuids, color, brightness }),
  smallrigCct: (uuids, kelvin, brightness, gm) => ipcRenderer.invoke('smallrig:cct', { uuids, kelvin, brightness, gm }),
  smallrigRgbw: (uuids, r, g, b, w) => ipcRenderer.invoke('smallrig:rgbw', { uuids, r, g, b, w }),
  smallrigFx: (uuids, mode, param1, param2) => ipcRenderer.invoke('smallrig:fx', { uuids, mode, param1, param2 }),
  smallrigStatus: (uuid) => ipcRenderer.invoke('smallrig:status', { uuid }),
  getStatus: () => ipcRenderer.invoke('runtime:status'),
  setAutoLaunch: (enabled) => ipcRenderer.invoke('auto-launch:set', enabled),
  onStatus: (callback) => ipcRenderer.on('runtime:status', (_event, status) => callback(status)),
  getCloudStatus: () => ipcRenderer.invoke('cloud:status'),
  onCloudStatus: (callback) => ipcRenderer.on('cloud:status', (_event, cloudStatus) => callback(cloudStatus)),
  getIntegrationStatus: () => ipcRenderer.invoke('integration:status'),
  onIntegrationStatus: (callback) => ipcRenderer.on('integration:status', (_event, status) => callback(status)),
  pairingStart: (options) => ipcRenderer.invoke('pairing:start', options),
  pairingCancel: () => ipcRenderer.invoke('pairing:cancel'),
  onPairingStatus: (callback) => ipcRenderer.on('pairing:status', (_event, status) => callback(status)),
  disconnect: () => ipcRenderer.invoke('cloud:disconnect'),
  getUpdateStatus: () => ipcRenderer.invoke('update:status'),
  onUpdateStatus: (callback) => ipcRenderer.on('update:status', (_event, status) => callback(status)),
  installUpdate: () => ipcRenderer.invoke('update:install')
});
